name: CI on Vector DB push to Milestone4

on:
  push:
    branches:
      - milestone4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - id: 'auth'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache Docker Compose binary
      id: docker-compose-cache
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/docker-compose
        key: docker-compose-${{ runner.os }}
  
    - name: Install Docker Compose if not cached
      if: steps.docker-compose-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies with Pipenv
      run: pipenv install 

    # Install pytest and pytest-cov for coverage
    - name: Install pytest and pytest-cov
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 pandas chromadb google-cloud-storage vertexai langchain langchain_community

    # Create Docker network before starting services
    - name: Create Docker network
      run: |
        docker network inspect bloodwise-network >/dev/null 2>&1 || docker network create bloodwise-network
        docker network ls

    # Build the local image first
    - name: Build Docker image
      run: |
        cd ${{ github.workspace }}/src/vector-db/
        docker build -t bloodwise-vector-db-cli -f Dockerfile .
        docker images

    - name: Build and start services with Docker Compose
      env:
        GCP_PROJECT: bloodwise-ai
        GCP_ZONE: us-central1-a
        GCS_SERVICE_ACCOUNT: llm-service-account@bloodwise-ai.iam.gserviceaccount.com
        GOOGLE_APPLICATION_CREDENTIALS: /workspace/credentials.json
        GCS_BUCKET_NAME: bloodwise-rag-knowledge-base
        
      run: |
        cd ${{ github.workspace }}/src/vector-db/
        docker-compose -f docker-compose.yml up -d \
            -v /tmp/credentials.json:/workspace/credentials.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/workspace/credentials.json \
            -e GCP_PROJECT=${GCP_PROJECT} \
            -e GCP_ZONE=${GCP_ZONE} \
            -e GCS_SERVICE_ACCOUNT=${GCS_SERVICE_ACCOUNT} \
            -e GCS_BUCKET_NAME=${GCS_BUCKET_NAME} 
        pytest tests/test_db.py -v 

    - name: Tear down services
      if: always()
      run: |
        cd ${{ github.workspace }}/src/vector-db/
        docker-compose down






            