name: CI on Vector DB push to Milestone4

on:
  push:
    branches:
      - milestone4  # Triggers when code is pushed to the milestone4 branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

       # Step 3: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

     # Step 4: Create Docker network
      - name: Create Docker network
        run: docker network create bloodwise-network || true

     # Step 5: Write GCP credentials
      - name: Prepare credentials
        run: |
          mkdir -p secrets
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > secrets/llm-service-account.json

     # Step 6: Build and run services
      - name: Build and run services
        env:
          GCP_PROJECT: bloodwise-ai
          GOOGLE_APPLICATION_CREDENTIALS: /secrets/llm-service-account.json
          IMAGE_NAME: bloodwise-vector-db-cli
        run: |
          cd ${{ github.workspace }}/vector-db/
          docker build -t $IMAGE_NAME -f Dockerfile .
          docker-compose up -d chromadb

          sleep 10
          
          docker-compose run --rm \
            -e GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS \
            -e GCP_PROJECT=$GCP_PROJECT \
            bloodwise-vector-db-cli \
            pipenv run pytest

     # Step 7: Cleanup
      - name: Cleanup
        if: always()
        run: |
          cd ${{ github.workspace }}/vector-db/
          docker-compose down
          docker network rm bloodwise-network || true



            